project:
  type: website
  preview:
    port: 8800
    browser: false
  output-dir: docs
  render:
    # - pages/*.ipynb
    - pages/*.qmd
    - slides/*.qmd

website:
  title: "ki-wb-gesundheit"
  navbar:
    left:
      - href: pages/index.qmd
        text: Home
      - pages/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



