project:
  type: website
  preview:
    port: 8800
    browser: false
  output-dir: docs
  render:
    # - pages/*.ipynb
    - pages/*.qmd
    - slides/*.qmd

website:
  title: "KI Weiterbildung Gesundheit //"
  site-url: https://virtuelleakademie.github.io/ki-wb-gesundheit
  repo-url: https://github.com/virtuelleakademie/ki-wb-gesundheit
  # repo-actions: [edit, issue]
  favicon: /assets/robot.png
  open-graph: true
  search:
    location: navbar
    type: overlay
    # type: textbox
  twitter-card:
    creator: "@awellis"
    card-style: summary_large_image

  reader-mode: false
  page-navigation: true
  back-to-top-navigation: true

  # Bootstrap icons: https://icons.getbootstrap.com/
  navbar:
    # title: false
    # logo: /assets/robot.png
    background: light
    left:
      # - text: "🏠 Home"
      #   file: pages/index.qmd
      - icon: calendar-event #house-door
        text: "Inhalt" # {{< fa calendar >}}
        file: pages/index.qmd

      - icon: file-slides
        text: "Dokumente" 
        menu:
          - text: "Begleitdokument: KI Weiterbildung"
            file: assets/begleitdokument-KI-weiterbildung.pdf
          - text: "Präsentation: KI in Pflegepraxis und Berufsbildung"
            file: assets/2024-09-09_KI-Pflegepraxis-Berufsbildung.pdf
          

      - icon: brush #pencil-square
        text: "Übungen"
        menu:
          # - text: "Activities"
          #   file: pages/activities.qmd
          - text: "Praktisches Üben"
            file: assets/uebungen.pdf
          # - text: "Activity"
          #   file: pages/activity.qmd

      # - icon: book
      #   text: "Tutorials"
      #   menu:
      #     - text: "Text representation: embeddings"
      #       # file: pages/text-representation.qmd

      # - icon: archive
      #   text: "Archive"
      #   menu:
      #     - text: "Part 1: What is ChatGPT?"
      #       # file: slides/00-introduction.qmd

      - icon: wrench-adjustable #tools
        text: "Links"
        menu:
          - text: "BFH Ressourcen"
            file: pages/resources.qmd
          # - text: "Tools"
          #   file: pages/tools.qmd

    tools:
      # - icon: robot
      #   text: Assistant
      #   file: pages/assistant.qmd
      - icon: lightbulb-fill
        text: Knowledge Base
        href: https://virtuelleakademie.ch/knowledge-base/
      # - icon: twitter
      #   href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/virtuelleakademie/ki-wb-gesundheit/
          - text: Report a Bug
            url:  https://github.com/virtuelleakademie/ki-wb-gesundheit/issues
  # sidebar:
  #   - title: "Slides 📺"
  #     style: "docked"
  #     background: light
  #     contents:
  #       - text: "The busy lecturer's guide to LLMs"
  #         file: slides/busy-lecturers-guide.qmd
  #       - text: "Part 1: What is ChatGPT?"
  #         file: slides/00-introduction.qmd
  #   - title: "🎓 Tutorials"
  #     style: "docked"
  #     background: light
  #     contents:
  #       - text: "Using the API: Prompting Programmatically"
  #         file: pages/prompting.qmd
page-footer:
    right:
    - icon: github
      href: https://github.com/virtuelleakademie/ki-wb-gesundheit

format:
  html:
    theme:
      light: simplex
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: true
    # linkcolor: rebeccapurple
comments:
  hypothesis:
    theme: clean
  # utterances:
    # repo: virtuelleakademie/ki-wb-gesundheit

execute:
  cache: true
  freeze: auto
  execute-dir: project

editor:
  render-on-save: true
