---
title: "Inhalt"
lightbox: auto
---
<!-- In this workshop, we will investigate how Large Language Models (LLMs) are trained, how they produce text, and what they are capable of. We will also discuss similarities and differences between LLMs and human thought processes. As LLMs become increasingly human-like in their performance, it is important to develop effective ways to describe their behaviour. We will discuss high-level concepts that allow us think about LLMs without falling into the trap of anthropomorphism. -->
<!-- TODO: fix schedule -->

<!-- ## {{< bi book >}} Contents -->


<!-- - How can I use LLMs in educational settings? -->

## {{< bi file-slides >}} Dokumente

{{< bi link >}} [Präsentation: Einführung](../assets/KI_Schulung_20251111.pdf )

{{< bi link >}} [Präsentation: KI in Pflegepraxis und Berufsbildung](../assets/2024-09-09_KI-Pflegepraxis-Berufsbildung.pdf)

{{< bi link >}} [Begleitdokument: KI Weiterbildung](../assets/begleitdokument-KI-weiterbildung.pdf)


## {{< bi brush >}} Übungen

{{< bi link >}} [Praktisches Üben](../assets/uebungen-2.pdf)

{{< bi link >}} [Gesprächsprotokoll](../assets/1602_FP_6_Sem_alle Prozesse.pdf)

{{< bi link >}} [Vorlage Förderungsplan](../assets/foerderungsplan-vorlage.pdf)

{{< bi link >}} [Taxonomieraster: Kompetenzentwicklung anhand der Niveaus und Perspektiven](../assets/Taxonomieraster_Typ_I.pdf)

{{< bi link >}} [Kriterienraster](../assets/Kriterienraster_alle%20Praxismodule.pdf)


## {{< bi house-door >}} Take-home messages

- KI-basierte Systeme können zur Optimierung des Ressourcenmanagements beitragen.

- Die ethische Anwendung und der Schutz sensibler Daten müssen stets gewährleistet sein.

